namespace: default
app: wordpress

mysql:
  image: mysql:8.0
  pass: CHANGE_ME
  mountPath: /var/lib/mysql
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
  port: 3306

wp:
  image: wordpress:6.2.1-apache
  mountPath: /var/www/html
  port: 80
  nodePort: 32000

  
