apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        tier: mysql
    spec:
      containers:
      - image: {{ .Values.mysql.image }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.pass }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.MYSQL_DATABASE }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.MYSQL_USER }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.pass }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: {{ .Values.mysql.mountPath }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
