apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
spec:
  ports:
    - port: {{ .Values.mysql.port }}
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
