apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.wp.image }}
        name: {{ .Values.app }}
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.mysql.pass }}
        - name: WORDPRESS_DB_USER
          value: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: {{ .Values.wp.mountPath }}
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
